### ISSUE TITLE
Can't see log level config

### ISSUE THREAD

**Issue by foxy82** [hassio-addons/addon-zwavejs2mqtt#54] opened 2021-02-21 17:09 UTC
# Problem/Motivation

> (Why the issue was filed)

From the addon documentation I should be able to set the log level:

> Option: log_level
> The log_level option controls the level of log output by the addon and can be changed to be more or less verbose, which might be useful when you are dealing with an unknown issue. Possible values are:
> 

However there is no where to insert this as the addon doesn't have a section that is editable.

## Expected behavior

> (What you expected to happen)

I expect to be able to type in the yaml config option 

## Actual behavior

> (What actually happened)

These is no where to type in the yaml config option

## Steps to reproduce

> (How can someone else make/see it happen)

Install the zwavejs2mqtt add on and try to configure log level.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment] 2021-02-21 17:11
Duplicate of #53

**Closed by sinclairpaul** 2021-02-21 17:11 UTC
