### ISSUE TITLE
UI store page is not able to show contents of files

### ISSUE THREAD

**Issue by wauswaus** [hassio-addons/addon-zwavejs2mqtt#23] opened 2021-02-06 12:41 UTC
# Problem/Motivation

The files that are showed in the store page of the UI cannot be showed. Clicking a file gives a "status request failed with status code 404" banner in the window below:

![afbeelding](https://user-images.githubusercontent.com/70056029/107118324-92a01780-6880-11eb-9dd8-a0ddeefad04c.png)

## Expected behavior

If I selected a file, the contents is shown in the colomn on the right.

## Actual behavior

Clicking a file gives a "status request failed with status code 404" banner in the window below.
Also downloading the files does not work properly.

In the log I see:
`
2021-02-06 13:35:09.948 INFO APP: GET /api/store//data/store/settings.json 404 3.092 ms - 1364
Error: Not Found
    at /opt/app.js:452:15
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/node_modules/express/lib/router/index.js:317:13)
    at /opt/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/node_modules/express/lib/router/index.js:275:10)
    at cors (/opt/node_modules/cors/lib/index.js:188:7)
    at /opt/node_modules/cors/lib/index.js:224:17
    at originCallback (/opt/node_modules/cors/lib/index.js:214:15)
    at /opt/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/opt/node_modules/cors/lib/index.js:199:9)
    at corsMiddleware (/opt/node_modules/cors/lib/index.js:204:7)
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/node_modules/express/lib/router/index.js:317:13)
    at /opt/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/node_modules/express/lib/router/index.js:335:12)
`

## Steps to reproduce

Click a file in the store.

**Comment by frenck** [comment] 2021-02-06 15:44
Duplicate of #4

**Closed by frenck** 2021-02-06 15:44 UTC
