### ISSUE TITLE
Dead device issue

### ISSUE THREAD

**Issue by Masterz69** [hassio-addons/addon-zwavejs2mqtt#62] opened 2021-02-26 22:58 UTC
Disconnected one ZWave plug from powers.
First issue: device become Dead after 15+ minutes only. May be it is ok, not sure.
Second issue: when issue turn_on/off commands towards Dead device - errors thrown in log, 
* as well as commands towards Alive devices goes very slow - with noticeable delay.
Third issue: Dead device still active in HA UI - all switches possible to toggle. Thats not good.

zwave_js_server.exceptions.FailedCommand: Command failed: unknown_error
2021-02-27 00:54:04 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547647517264] Command failed: unknown_error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/switch.py", line 64, in async_turn_off
    await self.info.node.async_set_value(target_value, False)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 250, in async_set_value
    result = await self.client.async_send_command(
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/client.py", line 64, in async_send_command
    return await future
zwave_js_server.exceptions.FailedCommand: Command failed: unknown_error

**Comment by Masterz69** [comment] 2021-02-27 07:49
Re-checked on 0.5.0 version.

Right aftetr sending command (by pressing switch in HA UI, f.e.) to already Dead device:
* all other ZWave actions/commands blocked during some (timeout?) period, approx. 15+ seconds....

As well Dead ZWave device still displayed as available/online in HA UI.
But MUST be shown with Status = Unavailable. 

And error looks same:
2021-02-27 09:45:11 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall switch.turn_on (c:803592e54a5cee9a7beba7e31eb3fe50): entity_id=['switch.plug_neo_03_switch']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1471, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/switch.py", line 58, in async_turn_on
    await self.info.node.async_set_value(target_value, True)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 250, in async_set_value
    result = await self.client.async_send_command(
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/client.py", line 64, in async_send_command
    return await future
zwave_js_server.exceptions.FailedCommand: Command failed: unknown_error

**Comment by Masterz69** [comment] 2021-02-27 08:01
After powering device again - first command proceeded with delay,
As well as commands to other devices - too.
But no error on log.

May be this is coinsidence - add-on Control Panel freezed for some time after device re-powered and go back to network.

**Comment by frenck** [comment] 2021-02-28 11:27
Duplicate of #63

**Closed by frenck** 2021-02-28 11:27 UTC
